# Generated by Django 4.1.9 on 2023-05-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmet_detection",
            name="artefact",
            field=models.ImageField(
                upload_to="C:\\Users\\LENOVO\\PycharmProjects\\Visual-Analytics\\Visual_Analytics\\output"
            ),
        ),
    ]
