# Generated by Django 4.1.9 on 2023-05-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_helmet_detection_artefact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmet_detection",
            name="artefact",
            field=models.ImageField(upload_to="output/"),
        ),
    ]
