# Generated by Django 4.1.9 on 2023-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_helmet_detection_artefact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helmet_detection",
            name="artefact",
            field=models.ImageField(upload_to="result/"),
        ),
    ]
