# Generated by Django 4.1.9 on 2023-05-18 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="helmet_detection",
            fields=[
                ("violation_id", models.AutoField(primary_key=True, serialize=False)),
                ("violation_type", models.CharField(max_length=20)),
                ("time_stamp", models.DateTimeField(default=datetime.datetime.now)),
                ("camera_number", models.CharField(max_length=20)),
                ("supervisor_remark", models.CharField(max_length=50)),
                ("artefact", models.ImageField(upload_to="C:\\output")),
                ("message", models.CharField(max_length=50)),
            ],
        ),
    ]
