# Generated by Django 4.1.9 on 2023-05-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="helmet_detection",
        ),
    ]
